### PR TITLE
Add x13a/zig-scrypt

### PR DESCRIPTION
**Pull request by The-King-of-Toasters**

### CODE REVIEW

**Comment by x13a** [comment]
This library is waiting for std. I already made a pull request for that when zig was version 0.7.1, but haven't time to complete. In near future, maybe next week (can't promise) I will redo that.

**Comment by The-King-of-Toasters** [comment]
Sounds good, I'm using this library on it's own but I might as well wait. BTW, do you think it's possible to make a comptime kdf function if `params` and `derived_key.len` is known at compile time?

**Comment by x13a** [comment]
I don't know zig well enough to help you. This was a golang port heavy modified by @jedisct1. Maybe he answer this.

**Comment by x13a** [comment]
The stopper with comptime scrypt can be that it requires much memory allocation (depends on params). This is done on the heap. Can zig allocate memory on the heap at comptime?

**Comment by jedisct1** [comment]
That would be abysmally slow!

What is the use case for running a CPU-hard/memory-hard function at comptime?

**Comment by jedisct1** [comment]
`@setEvalBranchQuota` would also need to be tuned accordingly, and even with very low parameters, that would be out of control.

**Comment by The-King-of-Toasters** [comment]
I had a look again and realised my error, my params would result in a 16k stack! Disregard.

**Comment by jedisct1** [comment]
16MB (not 16k) memory is the minimum for scrypt, even in low security settings.

**Pull request closed without merging**
